version: '3.9'
services:
   node-api:
      build: ./node-api
      container_name: node-api_container
      ports:
         - '5040:5050'
      volumes:
         - ./node-api:/node-api
         - ./node-api/node_modules
   react-frontend:
      build: ./react-frontend
      container_name: react-frontend_container
      ports:
         - '8080:3000'
      volumes:
         - ./react-frontend:/react-frontend
         - ./react-frontend/node_modules
      stdin_open: true
      tty: true
