version: '3.9'
services:
   node-api:
      build: ./node-api
      container_name: node-api_container
      ports:
         - '5040:5050'
      volumes:
         - ./node-api:/app
         - ./app/node_modules
   react-frontend:
      build: ./react-frontend
      container_name: react-frontend_container
      ports:
         - '3001:3001'
      # volumes:
      #    - ./react-frontend:/app
      #    - ./app/node_modules
      stdin_open: true
      tty: true
